# Generated by Django 5.2.8 on 2025-11-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='creator',
        ),
    ]
