# Generated by Django 6.0.5 on 2026-05-15 08:18

import asset.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_asset_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to='assets/', validators=[asset.validators.validate_file_size, asset.validators.validate_file_type]),
        ),
    ]
