# Generated by Django 5.2.8 on 2026-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timer_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
