# Generated by Django 6.0.5 on 2026-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_time_taken_task_timer_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='blocking', to='task.task'),
        ),
    ]
