# Generated by Django 6.0.5 on 2026-05-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
