# Generated by Django 6.0.1 on 2026-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_taskactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'Todo'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Done', 'Done')], default='To Do', max_length=20),
        ),
    ]
