# Generated by Django 6.0.5 on 2026-05-15 08:18

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_onetimepassword_delete_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='expires_at',
            field=models.DateTimeField(default=user.models._otp_default_expiry),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='otp',
            field=models.CharField(max_length=64),
        ),
    ]
